apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-controllers
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: false
  resources:
    requests:
      cpu: "200m"
      memory: 512Mi
    limits:
      cpu: "500m"
      memory: 1Gi

